name: NTop PR CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        run: cmake --build . --config Release
